export const studentData = [
  {
    studentId: "s1",
    name: "Anna",
    courses: [
      {
        courseId: "c1",
        courseName: "Intro to AI",
        progress: 0.85,
        completed: false,
        attempts: 4,
        averageScore: 52,
        timeOnTaskMinutes: 190,
        lastActivity: "2025-05-10T10:30:00Z",
      },
      {
        courseId: "c2",
        courseName: "Data Ethics",
        progress: 1.0,
        completed: true,
        attempts: 1,
        averageScore: 92,
        timeOnTaskMinutes: 140,
        lastActivity: "2025-05-19T08:00:00Z",
      },
      {
        courseId: "c3",
        courseName: "Machine Learning",
        progress: 0.45,
        completed: false,
        attempts: 3,
        averageScore: 70,
        timeOnTaskMinutes: 110,
        lastActivity: "2025-05-20T14:45:00Z",
      },
    ],
  },
  {
    studentId: "s2",
    name: "Alex",
    courses: [
      {
        courseId: "c1",
        courseName: "Intro to AI",
        progress: 0.25,
        completed: false,
        attempts: 1,
        averageScore: 55,
        timeOnTaskMinutes: 45,
        lastActivity: "2025-05-20T09:30:00Z",
      },
      {
        courseId: "c2",
        courseName: "Data Ethics",
        progress: 1.0,
        completed: true,
        attempts: 2,
        averageScore: 88,
        timeOnTaskMinutes: 180,
        lastActivity: "2025-05-15T11:20:00Z",
      },
      {
        courseId: "c3",
        courseName: "Machine Learning",
        progress: 0.75,
        completed: false,
        attempts: 4,
        averageScore: 65,
        timeOnTaskMinutes: 210,
        lastActivity: "2025-05-21T13:50:00Z",
      },
      {
        courseId: "c4",
        courseName: "Python Basics",
        progress: 0.6,
        completed: false,
        attempts: 1,
        averageScore: 78,
        timeOnTaskMinutes: 90,
        lastActivity: "2025-05-20T10:00:00Z",
      },
      {
        courseId: "c5",
        courseName: "Natural Language Processing",
        progress: 0.95,
        completed: false,
        attempts: 2,
        averageScore: 91,
        timeOnTaskMinutes: 130,
        lastActivity: "2025-05-22T08:10:00Z",
      },
    ],
  },
  {
    studentId: "s3",
    name: "John",
    courses: [
      {
        courseId: "c1",
        courseName: "Intro to AI",
        progress: 1.0,
        completed: true,
        attempts: 1,
        averageScore: 98,
        timeOnTaskMinutes: 160,
        lastActivity: "2025-05-19T18:30:00Z",
      },
      {
        courseId: "c2",
        courseName: "Data Ethics",
        progress: 0.5,
        completed: false,
        attempts: 2,
        averageScore: 65,
        timeOnTaskMinutes: 60,
        lastActivity: "2025-05-18T15:00:00Z",
      },
      {
        courseId: "c3",
        courseName: "Machine Learning",
        progress: 0.9,
        completed: false,
        attempts: 3,
        averageScore: 88,
        timeOnTaskMinutes: 220,
        lastActivity: "2025-05-21T09:00:00Z",
      },
      {
        courseId: "c4",
        courseName: "Python Basics",
        progress: 0.95,
        completed: false,
        attempts: 2,
        averageScore: 86,
        timeOnTaskMinutes: 140,
        lastActivity: "2025-05-20T07:45:00Z",
      },
      {
        courseId: "c5",
        courseName: "Natural Language Processing",
        progress: 0.15,
        completed: false,
        attempts: 1,
        averageScore: 43,
        timeOnTaskMinutes: 30,
        lastActivity: "2025-05-15T10:00:00Z",
      },
    ],
  },
];
